updated yaml

diff --git a/.github/workflows/nuget-publish.yml b/.github/workflows/nuget-publish.yml
--- a/.github/workflows/nuget-publish.yml
+++ b/.github/workflows/nuget-publish.yml
@@ -34,7 +34,16 @@ jobs:
         run: dotnet pack ./DotnetStandardSDK/DotnetStandardSDK/DotnetStandardSDK.csproj --configuration Release --no-build --output ./nupkg
 
       - name: List files in ./nupkg directory
-        run: dir ./nupkg  # Check if the .nupkg file is present
+        run: dir ./nupkg
 
-      - name: Publish the package to GitHub Packages 
-        run: dotnet nuget push D:/a/sdk_test/sdk_test/DotnetStandardSDK/DotnetStandardSDK/bin/Release/GraphXSDKClient.1.0.0.nupkg --source GitHubPackages --api-key ${{ secrets.GITHUB_TOKEN }}
+      - name: Check if .nupkg file exists
+        run: |
+          if (Test-Path "./nupkg/*.nupkg") {
+            echo ".nupkg file found!"
+          } else {
+            echo ".nupkg file not found!"
+            exit 1
+          }
+
+      - name: Publish the package to GitHub Packages
+        run: dotnet nuget push ./nupkg/GraphXSDKClient.1.0.0.nupkg --source GitHubPackages --api-key ${{ secrets.GITHUB_TOKEN }}
